import { parse } from "node-html-parser"

import { extractYoutubeVideoId } from "@bomy/shared/youtube"

// Minimum plain-text length (after entity decoding, tag stripping, and Unicode
// format-character removal) required for a Brand Story to count as "real text" —
// an admin-provisioning-only quality gate. Deliberately not part of the shared
// sanitizer: product bodies and a seller's own later Settings-page edits should
// not inherit this stricter, admin-only business rule.
export const BRAND_STORY_MIN_CHARS = 20

// Matches every Unicode "format" codepoint (category Cf — zero-width spaces/joiners,
// bidi embedding/override controls, BOM, etc.) via a Unicode property escape rather
// than hand-enumerating codepoint ranges — correct for the whole category, not just
// the handful of characters someone happens to remember, and can't regress into a
// literal invisible character accidentally pasted into source.
const FORMAT_CHAR_RE = /\p{Cf}/gu

/**
 * Extracts readable plain text from sanitized HTML for the mandatory-content check.
 * Uses node-html-parser's textContent (which decodes entities, e.g. &nbsp; -> U+00A0)
 * rather than a regex tag-strip, then removes invisible Unicode format characters and
 * collapses whitespace (including U+00A0, which JS's \s matches).
 */
export function extractPlainText(html: string): string {
  // Ensure spaces between adjacent elements by normalizing ></  to  > <
  // so block elements don't concatenate their text content
  const normalized = html.replace(/>\s*</g, "> <")
  const decoded = parse(normalized).textContent
  return decoded.replace(FORMAT_CHAR_RE, "").replace(/\s+/g, " ").trim()
}

export type StoreProvisioningValidation =
  | { ok: true; bodyHtml: string; videoId: string }
  | { ok: false; error: string }

/**
 * Shared mandatory-field gate for both admin store-creation paths (approveInquiry,
 * createStore). Runs entirely before any DB write is attempted — callers must not open
 * a transaction until this returns { ok: true }, since withAdmin (packages/db) only
 * rolls back on a THROWN error, not a returned failure; validating after a partial
 * insert would risk committing a bad row.
 *
 * Was previously duplicated ~28 lines per call site and had already drifted (one site
 * didn't guard a non-string videoUrl, the other did) — extracted here so both call
 * sites share one implementation and can only diverge in how they report a failure
 * (approveInquiry returns { ok: false }, createStore throws), not in what they check.
 *
 * `storeId` is generated by the caller (not here) so the caller retains control of the
 * literal id used in its own INSERT — this function only validates against it.
 */
export async function validateStoreProvisioning(
  bodyHtml: unknown,
  videoUrl: unknown,
  storeId: string,
): Promise<StoreProvisioningValidation> {
  if (typeof videoUrl !== "string") {
    return { ok: false, error: "A valid YouTube video URL is required." }
  }
  const videoId = extractYoutubeVideoId(videoUrl.trim())
  if (!videoId) {
    return { ok: false, error: "A valid YouTube video URL is required." }
  }

  const S3_PUBLIC_URL = process.env["S3_PUBLIC_URL"] ?? ""
  try {
    const u = new URL(S3_PUBLIC_URL)
    if (u.protocol !== "https:") throw new Error()
  } catch {
    return { ok: false, error: "Server misconfigured: S3_PUBLIC_URL." }
  }

  if (typeof bodyHtml !== "string") {
    return { ok: false, error: "Brand Story is required." }
  }
  const { normalizeBodyHtml } = await import("@bomy/shared/body-sanitizer")
  const sanitized = normalizeBodyHtml(bodyHtml, { kind: "store", id: storeId }, S3_PUBLIC_URL)
  if (!sanitized.ok) {
    return { ok: false, error: `Brand Story: ${sanitized.error}` }
  }
  if (sanitized.canonicalHtml === null) {
    return { ok: false, error: "Brand Story is required." }
  }
  if (extractPlainText(sanitized.canonicalHtml).length < BRAND_STORY_MIN_CHARS) {
    return {
      ok: false,
      error: `Brand Story needs at least ${BRAND_STORY_MIN_CHARS} characters of actual text.`,
    }
  }

  return { ok: true, bodyHtml: sanitized.canonicalHtml, videoId }
}
